### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by rahuljain5**

### CODE REVIEW

**Comment by rahuljain5** [comment]
Nope,
previously even if your session had expired you could see all pages until you made a request to backend.
this api just authenticates the session on every page, even if no service is requested

**Comment by rahuljain5** [comment]
keeping app.js at end of page will force to authenticate session at the end.
of page after everything has loaded

**Comment by rahuljain5** [comment]
will think about it, this is temporary fix u can say.
probably next version will have better error handling.

**Comment by rahuljain5** [comment]
windows.history.back() gives undefined, not sure why :/

**Review by poornac — APPROVED** [review]

**Pull request merged**
